import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../models/application_model.dart';
import '../repositories/application_repository.dart';
import '../../authentication/providers/auth_provider.dart';

class BookingFormScreen extends ConsumerStatefulWidget {
  final String exhibitionId;
  final String boothId;

  const BookingFormScreen({
    super.key,
    required this.exhibitionId,
    required this.boothId,
  });

  @override
  ConsumerState<BookingFormScreen> createState() => _BookingFormScreenState();
}

class _BookingFormScreenState extends ConsumerState<BookingFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _companyNameController = TextEditingController();
  final _companyDescController = TextEditingController();
  final _profileController = TextEditingController();

  bool _isLoading = false;
  final List<String> _selectedAddOns = [];
  final List<String> _availableAddOns = ['Extra Table', 'Power Outlet', 'Spotlight', 'Wi-Fi Pro'];

  @override
  void dispose() {
    _companyNameController.dispose();
    _companyDescController.dispose();
    _profileController.dispose();
    super.dispose();
  }

  Future<void> _submitApplication() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);
      try {
        final user = ref.read(currentUserProvider);
        if (user == null) throw Exception('User not logged in');

        // ADD THESE TWO LINES to fetch the exhibition title
        final exDoc = await FirebaseFirestore.instance.collection('exhibitions').doc(widget.exhibitionId).get();
        final exTitle = exDoc.data()?['title'] ?? 'Unknown Exhibition';

        final application = ApplicationModel(
          id: '', // Generated by Firestore
          exhibitorId: user.uid,
          exhibitionId: widget.exhibitionId,
          exhibitionTitle: exTitle,
          boothIds: [widget.boothId],
          status: 'pending',
          companyName: _companyNameController.text.trim(),
          companyDesc: _companyDescController.text.trim(),
          exhibitProfile: _profileController.text.trim(),
          addOns: _selectedAddOns,
          createdAt: DateTime.now(),
        );

        await ref.read(applicationRepositoryProvider).submitApplication(application);

        if (mounted) {
          // Temporarily routing back to map. We will route to Wireframe 10 (Success) next!
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Application Submitted!'), backgroundColor: Colors.green),
          );
          context.go('/success');
        }
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      } finally {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Booth Application Form')),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(24.0),
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(color: Colors.blue.shade50, borderRadius: BorderRadius.circular(12)),
              child: Text(
                  'Applying for Booth: ${widget.boothId}',
                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.blueAccent)
              ),
            ),
            const SizedBox(height: 24),
            TextFormField(
              controller: _companyNameController,
              decoration: const InputDecoration(labelText: 'Company Name', border: OutlineInputBorder()),
              validator: (v) => v!.isEmpty ? 'Required' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _companyDescController,
              maxLines: 3,
              decoration: const InputDecoration(labelText: 'Company Description', border: OutlineInputBorder()),
              validator: (v) => v!.isEmpty ? 'Required' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _profileController,
              maxLines: 3,
              decoration: const InputDecoration(labelText: 'What will you exhibit?', border: OutlineInputBorder()),
              validator: (v) => v!.isEmpty ? 'Required' : null,
            ),
            const SizedBox(height: 24),
            const Text('Add-ons (Optional)', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8.0,
              children: _availableAddOns.map((addon) {
                final isSelected = _selectedAddOns.contains(addon);
                return FilterChip(
                  label: Text(addon),
                  selected: isSelected,
                  onSelected: (selected) {
                    setState(() {
                      if (selected) _selectedAddOns.add(addon);
                      else _selectedAddOns.remove(addon);
                    });
                  },
                );
              }).toList(),
            ),
            const SizedBox(height: 32),
            FilledButton(
              onPressed: _isLoading ? null : _submitApplication,
              style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
              child: _isLoading
                  ? const CircularProgressIndicator(color: Colors.white)
                  : const Text('Submit Application', style: TextStyle(fontSize: 16)),
            )
          ],
        ),
      ),
    );
  }
}